# Generated by Django 5.2.12 on 2026-05-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_type', models.CharField(choices=[('wedding_hall', 'Wedding Hall'), ('banquet_hall', 'Banquet Hall'), ('auditorium', 'Auditorium'), ('conference_hall', 'Conference Hall'), ('meeting_room', 'Meeting Room'), ('party_hall', 'Party Hall'), ('convention_center', 'Convention Center'), ('rooftop_venue', 'Rooftop Venue'), ('beach_venue', 'Beach Venue'), ('open_ground', 'Open Ground')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('capacity_category', models.CharField(blank=True, choices=[('intimate', 'Intimate'), ('classic', 'Classic'), ('grand', 'Grand'), ('elite', 'Elite')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='venues/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
